using HospitalManagement.Application.DTOs;
using HospitalManagement.Application.Interfaces;
using HospitalManagement.Domain.Entities;
using HospitalManagement.Domain.Enums;
using HospitalManagement.Domain.Interfaces;
namespace HospitalManagement.Application.Services;
public class LaboratoryService : ILaboratoryService
{
    private readonly IGenericRepository<LabTest> _tests; private readonly IGenericRepository<LabRequest> _requests; private readonly IGenericRepository<LabResult> _results; private readonly IGenericRepository<Patient> _patients; private readonly IGenericRepository<Appointment> _appointments; private readonly IGenericRepository<Doctor> _doctors;
    public LaboratoryService(IGenericRepository<LabTest> tests,IGenericRepository<LabRequest> requests,IGenericRepository<LabResult> results,IGenericRepository<Patient> patients,IGenericRepository<Appointment> appointments,IGenericRepository<Doctor> doctors)=>(_tests,_requests,_results,_patients,_appointments,_doctors)=(tests,requests,results,patients,appointments,doctors);
    public async Task<IEnumerable<LabTestDto>> GetTestsAsync()=>(await _tests.GetAllAsync()).OrderBy(x=>x.TestName).Select(x=>new LabTestDto{Id=x.Id,TestCode=x.TestCode,TestName=x.TestName,Category=x.Category,Price=x.Price,NormalRange=x.NormalRange,IsActive=x.IsActive});
    public async Task<int> SaveTestAsync(SaveLabTestDto dto,int? id=null) { var duplicate=(await _tests.FindAsync(x=>x.TestCode==dto.TestCode.Trim())).FirstOrDefault(); if(duplicate is not null&&duplicate.Id!=id)throw new InvalidOperationException("A test with this code already exists."); var test=id.HasValue?await _tests.GetByIdAsync(id.Value)??throw new KeyNotFoundException("Lab test not found."):new LabTest{CreatedOn=DateTime.UtcNow}; test.TestCode=dto.TestCode.Trim();test.TestName=dto.TestName.Trim();test.Category=dto.Category;test.Price=dto.Price;test.NormalRange=dto.NormalRange;test.IsActive=dto.IsActive; if(id.HasValue)_tests.Update(test);else await _tests.AddAsync(test);await _tests.SaveChangesAsync();return test.Id; }
    public async Task<int> CreateRequestAsync(CreateLabRequestDto dto) { if(!await _tests.ExistsAsync(dto.LabTestId)||!await _patients.ExistsAsync(dto.PatientId)||(dto.AppointmentId.HasValue&&!await _appointments.ExistsAsync(dto.AppointmentId.Value))||(dto.DoctorId.HasValue&&!await _doctors.ExistsAsync(dto.DoctorId.Value)))throw new ArgumentException("One or more selected records are invalid.");if((await _requests.FindAsync(x=>x.RequestNumber==dto.RequestNumber.Trim())).Any())throw new InvalidOperationException("A request with this number already exists.");var request=new LabRequest{RequestNumber=dto.RequestNumber.Trim(),LabTestId=dto.LabTestId,PatientId=dto.PatientId,AppointmentId=dto.AppointmentId,DoctorId=dto.DoctorId,RequestedOn=DateTime.UtcNow,CreatedOn=DateTime.UtcNow};await _requests.AddAsync(request);await _requests.SaveChangesAsync();return request.Id; }
    public async Task<int> RecordResultAsync(RecordLabResultDto dto) { var request=await _requests.GetByIdAsync(dto.LabRequestId)??throw new KeyNotFoundException("Lab request not found.");if((await _results.FindAsync(x=>x.LabRequestId==dto.LabRequestId)).Any())throw new InvalidOperationException("A result has already been recorded.");var result=new LabResult{LabRequestId=dto.LabRequestId,ResultValue=dto.ResultValue,Remarks=dto.Remarks,ReportedOn=DateTime.UtcNow,CreatedOn=DateTime.UtcNow};await _results.AddAsync(result);request.Status=LabRequestStatus.Completed;_requests.Update(request);await _results.SaveChangesAsync();return result.Id; }
}
